[package]
name = "ketra_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
char_data = {path = "../char_data"}
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
async-std = { version = "1.8.0", features = ["attributes"] }
tide = "0.16.0"
